// <auto-generated />
namespace StudentManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StudentContext5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentContext5));
        
        string IMigrationMetadata.Id
        {
            get { return "201706122040276_StudentContext5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
